package semantic

// propertyMappings is the centralized CLI-facing vocabulary for PRO property
// abbreviations. It is compiled from docs/关键字对照表.csv and
// docs/iot-basic-info/基础信息_属性.csv; callers use PublicName, while ID stays
// inside the Runtime adapter.
var propertyMappings = []PropertyMapping{
	{ID: internalPower, PublicName: FieldPower, Description: "开关", ValueType: "bool", Aliases: []string{"on", "开关", "灯开关 – power", "power"}},
	{ID: internalBrightness, PublicName: FieldBrightness, Description: "亮度", ValueType: "int", Aliases: []string{"level", "亮度", "brightness", "亮度 - level"}},
	{ID: internalColorTemperature, PublicName: FieldColorTemperature, Description: "色温", ValueType: "int", Aliases: []string{"color temperature", "colour temperature", "color_temperature", "色温", "colorTemperature"}},
	{ID: internalColor, PublicName: FieldColor, Description: "颜色", ValueType: "int", Aliases: []string{"colour", "rgb", "hex", "颜色", "color"}},
	{ID: "m", PublicName: FieldMode, Description: "模式（2-色温 1-色彩）", ValueType: "enum", Aliases: []string{"mode", "模式", "模式：色温或者颜色", "模式（2-色温 1-色彩）"}},
	{ID: "bhm", PublicName: "bathHeatMode", Description: "浴霸模式（1:干燥 2:除雾 3:快速除雾 4:极速加热 5:其他模式）", ValueType: "enum", Aliases: []string{"bath heat mode", "浴霸模式（1:干燥 2:除雾 3:快速除雾 4:极速加热 5:其他模式）"}},
	{ID: "act", PublicName: "sensorActive", Description: "传感器已激活", ValueType: "bool", Aliases: []string{"sensor active", "sensorActive", "传感器已激活"}},
	{ID: "alm", PublicName: "alarm", Description: "告警（是否被拆）", ValueType: "bool", Aliases: []string{"告警", "报警", "传感器有报警", "告警（是否被拆）"}},
	{ID: "dc", PublicName: "doorClosed", Description: "是否接触", ValueType: "bool", Aliases: []string{"door close", "door closed", "门是否关闭", "是否接触", "门是否关闭 （门磁）"}},
	{ID: "oc", PublicName: "occupancyDetected", Description: "当前是否有人", ValueType: "bool", Aliases: []string{"occupancy detected", "occupancyDetected", "人在", "有人", "当前是否有人（人在传感器）"}},
	{ID: "mv", PublicName: "motionDetected", Description: "有人经过", ValueType: "bool", Aliases: []string{"motion detected", "motion", "有人经过", "有人移动", "当前是否有人移动 （人动传感器）"}},
	{ID: "cp", PublicName: "currentPosition", Description: "当前开合度", ValueType: "int", Aliases: []string{"current position", "percentage of window covered", "当前开合度", "窗帘关闭百分比", "窗帘关闭百分比（0-全关，100-全开）"}},
	{ID: "tp", PublicName: "targetPosition", Description: "目标开合度", ValueType: "int", Aliases: []string{"target position", "target percentage", "target percentage of window to open", "目标开合度", "目标窗帘关闭百分比", "目标窗帘关闭百分比（0-全关，100-全开）"}},
	{ID: "bl", PublicName: "batteryLevel", Description: "当前电量", ValueType: "int", Aliases: []string{"battery level", "battery_percentage", "电量", "当前电量"}},
	{ID: "bc", PublicName: "batteryChargeable", Description: "是否可充电", ValueType: "bool", Aliases: []string{"battery chargeable", "是否可充电", "battery_chargeable"}},
	{ID: "bcg", PublicName: "batteryCharging", Description: "电池正在充电", ValueType: "bool", Aliases: []string{"battery charging", "是否充电中", "battery_charging", "电池正在充电"}},
	{ID: "do", PublicName: "delayOff", Description: "延时关闭（0-120min）", ValueType: "int", Aliases: []string{"delay off", "延时关闭", "延时关闭（0-120min）"}},
	{ID: "acp", PublicName: "airConditionerPower", Description: "空调开关", ValueType: "bool", Aliases: []string{"ac power", "air condition power", "空调开关", "空调开关设置（1-acp， 2-acp等）"}},
	{ID: "acm", PublicName: "airConditionerMode", Description: "空调模式", ValueType: "int", Aliases: []string{"ac mode", "air condition mode", "空调模式", "设置空调模式 （1-acm， 2-acm等）"}},
	{ID: "actt", PublicName: "airConditionerTargetTemperature", Description: "空调设定目标温度", ValueType: "int", Aliases: []string{"ac target temperature", "空调设定温度", "air condition target temperature", "空调的设定温度 （1-actt， 2-actt等）", "空调设定目标温度"}},
	{ID: "acf", PublicName: "airConditionerFanSpeed", Description: "空调风速", ValueType: "int", Aliases: []string{"ac fan", "空调风速", "air condition fan speed", "空调的风速 （1-acf， 2-acf等）"}},
	{ID: "sp", PublicName: FieldSwitchPower, Description: "开关", ValueType: "bool", Aliases: []string{"switch power", "switchPower", "通道开关", "1. 如果是单通道设备，就用sp控制.", "开关"}},
	{ID: "blp", PublicName: "backlightPower", Description: "背光灯开关", ValueType: "bool", Aliases: []string{"backlight power", "背光灯开关", "1. 如果是单通道设备，就用 blp 控制."}},
	{ID: "acct", PublicName: "airConditionerCurrentTemperature", Description: "空调当前温度", ValueType: "int", Aliases: []string{"ac current temperature", "空调当前温度", "air condition current temperature", "空调的当前温度，只读 （1-acct， 2-acct等）"}},
	{ID: "aco", PublicName: "airConditionerOnline", Description: "是否在线", ValueType: "bool", Aliases: []string{"ac online", "空调在线", "air condition online", "空调在线状态 （1-aco， 2-aco等）", "是否在线"}},
	{ID: "acd", PublicName: "airConditionerDelay", Description: "延时开关剩余时间（毫秒）", ValueType: "int", Aliases: []string{"ac delay", "空调延时", "air condition delay", "空调开关延时 （1-acd， 2-acd等）", "延时开关剩余时间（毫秒）"}},
	{ID: "angle", PublicName: "angle", Description: "光束角", ValueType: "int", Aliases: []string{"光束角"}},
	{ID: "ebl", PublicName: "environmentalBrightnessLevel", Description: "环境亮度等级", ValueType: "int", Aliases: []string{"ll", "environment light level", "environmental brightness level", "环境亮度", "环境亮度等级"}},
	{ID: "acdfltr", PublicName: "acDeflector", Description: "空调挡风板角度", ValueType: "int", Aliases: []string{"ac deflector", "空调挡风板角度"}},
	{ID: "acrc", PublicName: "acRemoteController", Description: "儿童锁", ValueType: "int", Aliases: []string{"ac remote controller", "儿童锁"}},
	{ID: "ve", PublicName: "ventilation", Description: "换气档位：0: 关闭, 1: 低档, 2: 中档, 3: 高档", ValueType: "enum", Aliases: []string{"换气档位：0: 关闭, 1: 低档, 2: 中档, 3: 高档"}},
	{ID: "fa", PublicName: "fan", Description: "风扇档位：0: 关闭, 1: 低档, 2: 中档, 3: 高档", ValueType: "enum", Aliases: []string{"风扇档位：0: 关闭, 1: 低档, 2: 中档, 3: 高档"}},
	{ID: "he", PublicName: "heat", Description: "加热档位：0: 关闭, 1: 低档, 2: 中档, 3: 高档", ValueType: "enum", Aliases: []string{"加热档位：0: 关闭, 1: 低档, 2: 中档, 3: 高档"}},
	{ID: "h", PublicName: "humidity", Description: "当前湿度", ValueType: "int", Aliases: []string{"humidity", "current humidity", "湿度", "当前湿度", "当前湿度 （湿度传感器）"}},
	{ID: "t", PublicName: "currentTemperature", Description: "当前温度", ValueType: "int", Aliases: []string{"temperature", "current temperature", "温度", "当前温度", "当前温度 （温度传感器）"}},
	{ID: "tgt", PublicName: "targetTemperature", Description: "目标温度", ValueType: "int", Aliases: []string{"target temperature", "目标温度"}},
	{ID: "mppm", PublicName: "musicPlayerPlayMode", Description: "音乐播放器播放模式", ValueType: "int", Aliases: []string{"music player play mode", "音乐播放器播放模式"}},
	{ID: "mpmp", PublicName: "musicPlayerPlayPause", Description: "音乐播放器播放/暂停", ValueType: "bool", Aliases: []string{"music player play pause", "音乐播放器播放/暂停"}},
	{ID: "mpml", PublicName: "musicPlayerMusicList", Description: "音乐播放器歌单ID", ValueType: "bool", Aliases: []string{"music player music list", "音乐播放器歌单ID"}},
	{ID: "mpmr", PublicName: "musicPlayerMusicRhythm", Description: "音乐播放器音乐律动", ValueType: "int", Aliases: []string{"music player music rhythm", "音乐播放器音乐律动"}},
	{ID: "vol", PublicName: "volume", Description: "音量", ValueType: "int", Aliases: []string{"音量"}},
	{ID: "lc", PublicName: "lanControl", Description: "局域网控制开关", ValueType: "int", Aliases: []string{"lan control", "lanCtrl", "局域网控制", "R/W, 3rd party LAN control", "局域网控制开关"}},
	{ID: "li", PublicName: "indicatorSwitch", Description: "指示灯开关", ValueType: "int", Aliases: []string{"ledOn", "indicator switch", "指示灯开关", "R/W, 打开LED"}},
	{ID: "ip", PublicName: "ipAddress", Description: "ip地址", ValueType: "string", Aliases: []string{"ipAddr", "IP地址", "R/O, IP地址"}},
	{ID: "pl", PublicName: "networkState", Description: "有线/wifi", ValueType: "int", Aliases: []string{"physical link", "netState", "有线/wifi", "R/O, 1：有线， 0: 无线"}},
	{ID: "lf", PublicName: "uptime", Description: "上电时间", ValueType: "int", Aliases: []string{"up time", "lifeTime", "网关运行时间", "R/O, 网关运行时间", "上电时间"}},
	{ID: "fm", PublicName: "freeMemory", Description: "剩余内存", ValueType: "int", Aliases: []string{"memory free", "freeMem", "剩余内存", "R/O, 网关剩余内存"}},
	{ID: "ssid", PublicName: "wiFiSsid", Description: "wifi：id", ValueType: "string", Aliases: []string{"WiFi SSID", "热点名称", "R/W, 热点", "wifi：id"}, Sensitive: true},
	{ID: "slisaon", PublicName: "smartSwitch", Description: "是否开启闪断", ValueType: "int", Aliases: []string{"R/W, 使用凌动开关", "是否开启闪断"}},
	{ID: "bp", PublicName: "powerOnBoot", Description: "上电后状态", ValueType: "int", Aliases: []string{"power on boot", "actOnPower", "上电后状态", "battery_percentage", "电量", "R/W, 上电开灯"}},
	{ID: "rl", PublicName: "relayPower", Description: "是否开启relay", ValueType: "int", Aliases: []string{"relay", "relayOn", "R/W, 打开relay", "是否开启relay"}},
	{ID: "dt", PublicName: "curtainManualOperationAllowed", Description: "是否支持手拉", Aliases: []string{"是否支持手拉"}},
	{ID: "pi", PublicName: "curtainStartPositionCalibrated", Description: "起点是否设定", Aliases: []string{"起点是否设定"}},
	{ID: "pe", PublicName: "curtainEndPositionCalibrated", Description: "终点是否设定", Aliases: []string{"终点是否设定"}},
	{ID: "fv", PublicName: FieldFirmwareVersion, Description: "固件版本号", ValueType: "int", Aliases: []string{"firmware version", "firmwareVersion", "固件版本", "固件版本号"}},
	{ID: "pt", PublicName: "productType", Description: "产品类型", ValueType: "int", Aliases: []string{"ptype", "product type", "productType", "产品类型"}},
	{ID: "extend", PublicName: "extendInfo", Description: "投射配置", ValueType: "object", Aliases: []string{"extend info", "json", "投射配置"}},
	{ID: "rd", PublicName: "reverseDirection", Description: "电机方向是否反转", ValueType: "int", Aliases: []string{"reverse direction", "0/1，电机的方向和用户实际安装方向是否一致（0为一致）", "电机方向是否反转"}},
	{ID: "dd", PublicName: "defaultDuration", Description: "默认渐变时长", ValueType: "int", Aliases: []string{"default duration", "默认渐变时间attr", "默认渐变时长"}},
	{ID: "showGroupDevices", PublicName: "showGroupDevices", Description: "是否显示组内设备", ValueType: "bool", Aliases: []string{"是否显示组内设备"}},
	{ID: "eip", PublicName: "externalIP", Description: "外网ip", ValueType: "string", Aliases: []string{"external IP", "外网ip"}},
	{ID: "fblck", PublicName: "resetLock", Description: "重置锁定开关", ValueType: "int", Aliases: []string{"reset lock", "重置锁定开关"}},
	{ID: "fbnum", PublicName: "resetLockNum", Description: "重置次数", ValueType: "int", Aliases: []string{"reset lock num", "重置次数"}},
	{ID: "ntOn", PublicName: "nightModeOn", Description: "是否开启夜间", ValueType: "int", Aliases: []string{"night mode on", "是否开启夜间"}},
	{ID: "ntStart", PublicName: "nightModeStart", Description: "夜间模式开启时间", ValueType: "int", Aliases: []string{"night mode start", "夜间模式开启时间"}},
	{ID: "ntEnd", PublicName: "nightModeEnd", Description: "夜间模式结束时间", ValueType: "int", Aliases: []string{"night mode end", "夜间模式结束时间"}},
	{ID: "ntDelay", PublicName: "nightModeDelay", Description: "夜间模式延时", ValueType: "int", Aliases: []string{"night mode delay", "夜间模式延时"}},
	{ID: "hrbk", PublicName: "haierBindKey", Description: "通过海尔智家oauth获取到的用户token", ValueType: "string", Aliases: []string{"haier bind key", "通过海尔智家oauth获取到的用户token"}, Sensitive: true},
	{ID: "hrdm", PublicName: "haierDomain", Description: "海尔云平台连接域名", ValueType: "string", Aliases: []string{"haier domain", "海尔云平台连接域名"}, Sensitive: true},
	{ID: "hrpt", PublicName: "haierPort", Description: "海尔云平台连接端口", ValueType: "string", Aliases: []string{"haier port", "海尔云平台连接端口"}, Sensitive: true},
	{ID: "ch_num", PublicName: "numberOfChannels", Description: "组件数目", ValueType: "int", Aliases: []string{"Number of channels", "多通道设备，受控设备的通道数量", "channel num", "组件数目"}},
	{ID: "nightMode", PublicName: "nightMode", Description: "夜间模式配置", ValueType: "object", Aliases: []string{"night mode", "夜间模式配置"}},
	{ID: "slisaon_rdy", PublicName: "smartSwitchReady", Description: "是否支持闪断", ValueType: "int", Aliases: []string{"R/O, 支持凌动开关, 1:支持，0:不支持", "slisaon ready", "是否支持闪断"}},
	{ID: "psk", PublicName: "wiFiPassword", Description: "wifi密码", ValueType: "string", Aliases: []string{"password", "WiFi password", "wifi密码", "W/O, 密码"}, Sensitive: true},
	{ID: "hb_interval", PublicName: "heartBeatInterval", Description: "心跳间隔（暂未使用）", ValueType: "int", Aliases: []string{"heart beat interval", "心跳间隔（暂未使用）"}},
	{ID: "ttl", PublicName: "timeToLive", Description: "time to live（未使用）", ValueType: "int", Aliases: []string{"time to live", "time to live（未使用）"}},
	{ID: "retrans", PublicName: "retransNum", Description: "重传次数（未使用）", ValueType: "int", Aliases: []string{"retrans num", "重传次数（未使用）"}},
	{ID: "tx_power", PublicName: "transmitPower", Description: "发射功率", ValueType: "int", Aliases: []string{"transmit power", "发射功率"}},
	{ID: "jen", PublicName: "jogEnable", Description: "是否开启点动", ValueType: "int", Aliases: []string{"jog enable", "是否开启点动"}},
	{ID: "jdef", PublicName: "jogDefault", Description: "点动默认状态", ValueType: "int", Aliases: []string{"jog default", "点动默认状态"}},
	{ID: "jtm", PublicName: "jogTime", Description: "点动持续时间", ValueType: "int", Aliases: []string{"jog time", "点动持续时间"}},
	{ID: "open_type", PublicName: "openType", Description: "开启方向", ValueType: "int", Aliases: []string{"open type", "开启方向"}},
	{ID: "miln", PublicName: "registeredLinkedToMiot", Description: "mi linked, Yeelight Pro mesh网关是否绑定米家标志", ValueType: "int", Aliases: []string{"registered (linked) to miot", "R/O, bool型，网关专属，是否已经注册到米家", "mi linked", "mi linked, Yeelight Pro mesh网关是否绑定米家标志"}},
	{ID: "miid", PublicName: "registeredDidFromMiot", Description: "mi did, Yeelight Pro mesh 网关在米家的 did", ValueType: "string", Aliases: []string{"registered did from miot", "R/W, 网关专属，string, miot动态分配的did，例如“ 70000032455 ”", "mi did", "mi did, Yeelight Pro mesh 网关在米家的 did"}, Sensitive: true},
	{ID: "mibk", PublicName: "bindKeyReceivedFromMiot", Description: "mi bind key, Yeelight Pro mesh 网关在米家的 bind key", ValueType: "string", Aliases: []string{"bind key received from miot", "W/O, 网关专属 ，string ，绑定到miot时收到的token，例如\"uVHQAuvrxZVG3fau\"", "mi bind key", "mi bind key, Yeelight Pro mesh 网关在米家的 bind key"}, Sensitive: true},
	{ID: "micd", PublicName: "countryDomainReceivedFromMiot", Description: "mi country domain, Yeelight Pro mesh 网关在米家的 country domain", ValueType: "string", Aliases: []string{"country domain received from miot", "W/O, 网关专属 ，string ，绑定到miot时收到的country domain，例如\"us\" ，可为空", "mi country domain", "mi country domain, Yeelight Pro mesh 网关在米家的 country domain"}, Sensitive: true},
	{ID: "midk", PublicName: "regiesteredDeviceKeyFromMiot", Description: "mi device key, Yeelight Pro mesh 网关的在米家的device key", ValueType: "string", Aliases: []string{"regiestered device key from miot", "W/O, 网关专属 ，string ，miot动态分配的设备key,BASE64(key_value)", "mi device key", "mi device key, Yeelight Pro mesh 网关的在米家的device key"}, Sensitive: true},
	{ID: "ntScreenMode", PublicName: "nightScreenMode", Description: "屏保模式", ValueType: "int", Aliases: []string{"night screen mode", "屏保模式"}},
	{ID: "mp", PublicName: "mutexPower", Description: "互斥锁", ValueType: "int", Aliases: []string{"mutex power", "互斥锁"}},
	{ID: "mp_keys", PublicName: "multiPanelKeys", Description: "多功能屏的情景按键配置信息", ValueType: "object", Aliases: []string{"multi-panel keys", "多功能屏的情景按键配置信息"}},
	{ID: "mp_buttons", PublicName: "multiPanelButtons", Description: "多功能屏的主屏快捷键配置信息", ValueType: "object", Aliases: []string{"multi-panel buttons", "多功能屏的主屏快捷键配置信息"}},
	{ID: "mp_devices", PublicName: "multiPanelDevices", Description: "多功能屏中投射的子设备配置信息", ValueType: "object", Aliases: []string{"multi-panel devices", "多功能屏中投射的子设备配置信息"}},
	{ID: "mp_nightmode", PublicName: "multiPanelNightMode", Description: "多功能屏-复杂逻辑使用", ValueType: "object", Aliases: []string{"multi-panel night mode", "mp_nightMode", "多功能屏-复杂逻辑使用"}},
	{ID: "c_n_c", PublicName: "componentNumConfig", Description: "组件数目设置", ValueType: "int", Aliases: []string{"component num config", "component_num_config", "组件数目设置"}},
	{ID: "mei_login", PublicName: "meiLogin", Description: "当前网关是否已登录到美的云", ValueType: "int", Aliases: []string{"mei login", "当前网关是否已登录到美的云"}},
	{ID: "meiln", PublicName: "meiLinked", Description: "当前网关是否已入网绑定到美的云", ValueType: "int", Aliases: []string{"mei linked", "当前网关是否已入网绑定到美的云"}},
	{ID: "mei_info", PublicName: "meiInfo", Description: "美的设备身份信息", ValueType: "string", Aliases: []string{"mei info", "美的设备身份信息"}},
	{ID: "meibk", PublicName: "meiBindKey", Description: "bindkey", ValueType: "string", Aliases: []string{"mei bind key", "bindkey"}, Sensitive: true},
	{ID: "mei_did", PublicName: "meiDid", Description: "美的设备id", ValueType: "int64", Aliases: []string{"mei did", "美的设备id"}, Sensitive: true},
	{ID: "mei_all_nodes_sync_state", PublicName: "meiAllNodesSyncState", Description: "网关同步时子设备同步状态", ValueType: "int", Aliases: []string{"mei all nodes sync state", "网关同步时子设备同步状态"}},
	{ID: "plugins", PublicName: "plugins", Description: "网关三方插件信息", ValueType: "array", Aliases: []string{"网关三方插件信息"}},
	{ID: "height", PublicName: "height", Description: "高度", ValueType: "int", Aliases: []string{"高度"}},
	{ID: "tra", PublicName: "targetRotaryAngle", Description: "目标旋转角度", ValueType: "int", Aliases: []string{"target rotary angle", "目标旋转角度"}},
	{ID: "cra", PublicName: "currentRotaryAngle", Description: "当前旋转角度", ValueType: "int", Aliases: []string{"current rotary angle", "当前旋转角度"}},
	{ID: "rrd", PublicName: "tiltReverseDirection", Description: "角度是否反转", ValueType: "int", Aliases: []string{"tilt reverse direction", "角度是否反转"}},
	{ID: "rg", PublicName: "tiltRotationGears", Description: "角度旋转力度", ValueType: "int", Aliases: []string{"tilt rotation gears", "角度旋转力度"}},
	{ID: "mei_all_scenes_sync_state", PublicName: "meiAllScenesSyncState", Description: "美的情景同步状态", ValueType: "int", Aliases: []string{"mei all scenes sync state", "美的情景同步状态"}},
	{ID: "3rdPartySyncBitmask", PublicName: "thirdPartySyncBitmask", Description: "同步三方设定", ValueType: "int", Aliases: []string{"third party sync bitmask", "同步三方设定"}},
	{ID: "rmt", PublicName: "remoteManagement", Description: "遥控器信息", ValueType: "string", Aliases: []string{"remote management", "遥控器信息"}},
	{ID: "weather_hidden", PublicName: "weatherHidden", Description: "weather_hidden 在屏幕上隐藏天气信息；false：展示；true：隐藏", ValueType: "bool", Aliases: []string{"weather hidden", "weather_hidden 在屏幕上隐藏天气信息；false：展示；true：隐藏"}},
	{ID: "time_hidden", PublicName: "timeHidden", Description: "time_hidden 在屏幕上隐藏时间信息；false：展示；true：隐藏", ValueType: "bool", Aliases: []string{"time hidden", "time_hidden 在屏幕上隐藏时间信息；false：展示；true：隐藏"}},
	{ID: "temp_hidden", PublicName: "temperatureHidden", Description: "temperature_hidden，在屏幕上隐藏温度信息. false：展示, true：隐藏；", ValueType: "bool", Aliases: []string{"temperature hidden", "temperature_hidden，在屏幕上隐藏温度信息. false：展示, true：隐藏；"}},
	{ID: "keys_visible", PublicName: "keysVisible", Description: "按键是否显示", ValueType: "int", Aliases: []string{"keys visible", "按键是否显示"}},
	{ID: "luminance", PublicName: "luminance", Description: "照度", ValueType: "int", Aliases: []string{"照度"}},
	{ID: "sonos_mgr", PublicName: "sonosManager", Description: "sonos开启关闭命令", ValueType: "bool", Aliases: []string{"sonos manager", "sonos开启关闭命令"}},
	{ID: "mp_scenes", PublicName: "multiPanelScenes", Description: "多功能屏设备情景按键列表", ValueType: "array", Aliases: []string{"multi-panel scenes", "多功能屏设备情景按键列表"}},
	{ID: "sens_range", PublicName: "senseRange", Description: "感应范围，传感器感应范围大小", ValueType: "int", Aliases: []string{"sense range", "感应范围，传感器感应范围大小"}},
	{ID: "lumi_setting", PublicName: "luminanceSetting", Description: "照度设置", ValueType: "int", Aliases: []string{"luminance setting", "照度设置"}},
	{ID: "hr_login", PublicName: "haierLogin", Description: "海尔云是否连接", ValueType: "int", Aliases: []string{"haier login", "海尔云是否连接"}},
	{ID: "hrln", PublicName: "haierLinked", Description: "设备绑定到海尔云状态", ValueType: "int", Aliases: []string{"haier linked", "设备绑定到海尔云状态"}},
	{ID: "hr_all_nodes_sync_state", PublicName: "haierAllNodesSyncState", Description: "三方同步到海尔设备状态", ValueType: "int", Aliases: []string{"haier all nodes sync state", "三方同步到海尔设备状态"}},
	{ID: "hr_all_scenes_sync_state", PublicName: "haierAllScenesSyncState", Description: "三方情景同步到海尔状态", ValueType: "int", Aliases: []string{"haier all scenes sync state", "三方情景同步到海尔状态"}},
	{ID: "delay_time", PublicName: "delayTime", Description: "延时时间", ValueType: "int", Aliases: []string{"delay time", "延时时间"}},
	{ID: "sdt", PublicName: "deviceTypeAfterRelaySwitch", Description: "继电器后边所接的设备类型", ValueType: "int", Aliases: []string{"device type after relay switch", "继电器后边所接的设备类型"}},
	{ID: "vmcp", PublicName: "vmcPower", Description: "开关", ValueType: "bool", Aliases: []string{"vmc power", "开关"}},
	{ID: "vmcf", PublicName: "vmcFan", Description: "风速", ValueType: "int", Aliases: []string{"vmc fan", "风速"}},
	{ID: "rfhp", PublicName: "rfhPower", Description: "地暖开关", ValueType: "bool", Aliases: []string{"rfh power", "地暖开关"}},
	{ID: "rfhct", PublicName: "rfhCurrentTemperature", Description: "地暖当前温度", ValueType: "int", Aliases: []string{"rfh current temperature", "地暖当前温度"}},
	{ID: "rfhtt", PublicName: "rfhTargetTemperature", Description: "地暖设定目标温度", ValueType: "int", Aliases: []string{"rfh target temperature", "地暖设定目标温度"}},
	{ID: "hk", PublicName: "homeKitLinked", Description: "当前网关是否已入网绑定到HomeKit", ValueType: "string", Aliases: []string{"当前网关是否已入网绑定到HomeKit"}},
	{ID: "mfl", PublicName: "matterLinked", Description: "当前网关是否已入网绑定到matter", ValueType: "enum", Aliases: []string{"当前网关是否已入网绑定到matter"}},
	{ID: "name", PublicName: "name", Description: "名称", ValueType: "string", Aliases: []string{"名称"}},
	{ID: "icon", PublicName: "icon", Description: "图标", ValueType: "string", Aliases: []string{"图标"}},
	{ID: "o", PublicName: FieldOnline, Description: "是否在线", ValueType: "bool", Aliases: []string{"online", "在线", "是否在线"}},
	{ID: "support_fblck", PublicName: "supportResetLock", Description: "是否支持重置锁定", ValueType: "bool", Aliases: []string{"support reset lock", "是否支持重置锁定"}},
	{ID: "cpt", PublicName: "connectivityProtocolsType", Description: "当前接入协议", ValueType: "int", Aliases: []string{"connectivity protocols type", "当前接入协议"}},
	{ID: "support_rl", PublicName: "supportRelay", Description: "是否支持relay", ValueType: "bool", Aliases: []string{"support relay", "是否支持relay"}},
	{ID: "mac", PublicName: "macAddress", Description: "mac地址", ValueType: "string", Aliases: []string{"MAC地址"}, Sensitive: true},
	{ID: "deviceKey", PublicName: "deviceKey", Description: "设备key", ValueType: "string", Aliases: []string{"device key", "设备key"}, Sensitive: true},
	{ID: "ltk", PublicName: "localToken", Description: "本地key", ValueType: "string", Aliases: []string{"local token", "本地key"}, Sensitive: true},
	{ID: "rs", PublicName: "routeSet", Description: "开关方向是否已校准", ValueType: "int", Aliases: []string{"route set", "开关方向是否已校准"}},
	{ID: "sbp", PublicName: "switchPowerOnBoot", Description: "上电状态", ValueType: "int", Aliases: []string{"switch power on boot", "上电状态"}},
	{ID: "mock", PublicName: "mockTarget", Description: "mock成什么", ValueType: "int", Aliases: []string{"mock成什么"}},
	{ID: "trs", PublicName: "tiltRouteSet", Description: "调光方向上是否校准", ValueType: "int", Aliases: []string{"tilt route set", "调光方向上是否校准"}},
	{ID: "io", PublicName: "ioType", Description: "是否为输入/输出组件，enum values {dummy, input, output, inout}, 后台定义组件时自动计算", ValueType: "int", Aliases: []string{"io type", "io_type", "是否为输入/输出组件，enum values {dummy, input, output, inout}, 后台定义组件时自动计算"}},
	{ID: "sa", PublicName: "swingAngle", Description: "摆动角度（60-120）", ValueType: "int", Aliases: []string{"swing angle", "摆动角度（60-120）"}},
	{ID: "ss", PublicName: "swingStart", Description: "摆动类型：1-循环摆动，0-固定角度", ValueType: "enum", Aliases: []string{"swing start", "摆动类型：1-循环摆动，0-固定角度"}},
	{ID: "rst", PublicName: "roomSizeType", Description: "房间大小：0-小于4平，1-4-6平，2-6-8平，3-大于8平", ValueType: "enum", Aliases: []string{"room size type", "房间大小：0-小于4平，1-4-6平，2-6-8平，3-大于8平"}},
	{ID: "dntm", PublicName: "deviceNightMode", Description: "夜间模式（设备专用）", ValueType: "object", Aliases: []string{"device night mode", "夜间模式（设备专用）"}},
	{ID: "run_power", PublicName: "runPower", Description: "设备运行功率 单位瓦", ValueType: "int", Aliases: []string{"run power", "设备运行功率 单位瓦"}},
	{ID: "life", PublicName: "expectedLifetimeHours", Description: "设备预期寿命 单位小时", ValueType: "int", Aliases: []string{"设备预期寿命 单位小时"}},
	{ID: "min_level", PublicName: "minLevel", Description: "设备的最小输出等级", ValueType: "int", Aliases: []string{"设备的最小输出等级"}},
	{ID: "max_level", PublicName: "maxLevel", Description: "设备的最大输出等级", ValueType: "int", Aliases: []string{"设备的最大输出等级"}},
	{ID: "power_on_level", PublicName: "powerOnLevel", Description: "上电默认亮度的配置，需要同时包含亮度、色温、色彩三个值", ValueType: "string", Aliases: []string{"上电默认亮度的配置，需要同时包含亮度、色温、色彩三个值"}},
	{ID: "system_failure_level", PublicName: "systemFailureLevel", Description: "设备异常时灯亮度，需要同时包含亮度、色温、色彩三个值", ValueType: "string", Aliases: []string{"设备异常时灯亮度，需要同时包含亮度、色温、色彩三个值"}},
	{ID: "fade_rate", PublicName: "fadeRate", Description: "渐变步长", ValueType: "int", Aliases: []string{"渐变步长"}},
	{ID: "dim_curve", PublicName: "dimCurve", Description: "功率亮度曲线：0表示对数函数，1表示线性函数", ValueType: "int", Aliases: []string{"功率亮度曲线：0表示对数函数，1表示线性函数"}},
	{ID: "dev_alarm", PublicName: "devAlarm", Description: "设备异常告警信息 具体内容网关自行设置", ValueType: "int", Aliases: []string{"设备异常告警信息 具体内容网关自行设置"}},
	{ID: "gtin", PublicName: "globalTradeItemNumber", Description: "gtin", ValueType: "int"},
	{ID: "ddt", PublicName: "daliDeviceType", Description: "dali dt", ValueType: "string", Aliases: []string{"dali dt"}},
	{ID: "ap", PublicName: "activePower", Description: "有功功率", ValueType: "int64", Aliases: []string{"active_power", "有功功率"}},
	{ID: "ae", PublicName: "activeEnergy", Description: "总有功", ValueType: "int64", Aliases: []string{"active_energy", "总有功"}},
	{ID: "ot", PublicName: "operatingTime", Description: "系统运行时间 单位秒", ValueType: "int", Aliases: []string{"operating_time", "系统运行时间 单位秒"}},
	{ID: "sys_s", PublicName: "systemStarts", Description: "系统启动次数", ValueType: "int", Aliases: []string{"system_starts", "系统启动次数"}},
	{ID: "esv", PublicName: "externalSupplyVoltage", Description: "供电电压 单位0.1V", ValueType: "int", Aliases: []string{"external_supply_voltage", "供电电压 单位0.1V"}},
	{ID: "esvf", PublicName: "externalSupplyVoltageFrequency", Description: "供电电压频率 单位Hz", ValueType: "int", Aliases: []string{"external_supply_voltage_frequency", "供电电压频率 单位Hz"}},
	{ID: "temp", PublicName: "temperature", Description: "温度", ValueType: "int", Aliases: []string{"温度"}},
	{ID: "ocp", PublicName: "outputCurrentPercent", Description: "输出电流百分比", ValueType: "int", Aliases: []string{"output_current_percent", "输出电流百分比"}},
	{ID: "lsot", PublicName: "lightSourceOnTime", Description: "开灯时长 单位秒", ValueType: "int", Aliases: []string{"light_source_on_time", "开灯时长 单位秒"}},
	{ID: "lsv", PublicName: "lightSourceVoltage", Description: "输出电压 单位0.1V", ValueType: "int", Aliases: []string{"light_source_voltage", "输出电压 单位0.1V"}},
	{ID: "lsc", PublicName: "lightSourceCurrent", Description: "输出电流 单位mA", ValueType: "int", Aliases: []string{"light_source_current", "输出电流 单位mA"}},
	{ID: "dver", PublicName: "daliVersion", Description: "DALI版本", ValueType: "int", Aliases: []string{"DALI版本"}},
	{ID: "dpt", PublicName: "daliSwitchType", Description: "dali开关类型 1 默认模式，2 亮度模式", ValueType: "int", Aliases: []string{"dali开关类型 1 默认模式，2 亮度模式"}},
	{ID: "ep", PublicName: "eventPriority", ValueType: "int", Aliases: []string{"event priority"}},
	{ID: "st", PublicName: "syncTime", ValueType: "int", Aliases: []string{"Sync Time flag", "short timers"}},
	{ID: "rt", PublicName: "repeatTimers", ValueType: "int", Aliases: []string{"repeat timers"}},
	{ID: "dead_time", PublicName: "deadTime", ValueType: "int"},
	{ID: "report_timers", PublicName: "reportTimers", ValueType: "int", Aliases: []string{"report timers"}},
	{ID: "hold_timers", PublicName: "holdTimers", ValueType: "int"},
	{ID: "hys", PublicName: "hysteresis", ValueType: "int"},
	{ID: "hys_min", PublicName: "hysteresisMin", ValueType: "int", Aliases: []string{"hysteresis_min"}},
	{ID: "level_limit_rdy", PublicName: "levelLimitRdy", Description: "是否支持功率限制", ValueType: "int", Aliases: []string{"是否支持功率限制"}},
	{ID: "dali_is_cnt", PublicName: "daliIsCnt", Description: "dali设备的光感组件数量", ValueType: "int", Aliases: []string{"dali设备的光感组件数量"}},
	{ID: "dali_hds_cnt", PublicName: "daliHdsCnt", Description: "dali设备的人感组件数量", ValueType: "int", Aliases: []string{"dali设备的人感组件数量"}},
	{ID: "dali_scb_cnt", PublicName: "daliScbCnt", Description: "dali设备的按键组件数量", ValueType: "int", Aliases: []string{"dali设备的按键组件数量"}},
	{ID: "pf", PublicName: "powerFactor", Description: "功率因数", ValueType: "int64", Aliases: []string{"功率因数"}},
	{ID: "run_speed", PublicName: "runSpeed", Description: "运行速度", ValueType: "int", Aliases: []string{"运行速度"}},
	{ID: "mimac", PublicName: "miMacAddress", Description: "小米mac地址", ValueType: "string", Aliases: []string{"小米mac地址"}, Sensitive: true},
	{ID: "ct_rdy", PublicName: "colorTemperatureSupported", Description: "是否支持色温", ValueType: "string", Aliases: []string{"是否支持色温"}},
	{ID: "run_speed_rdy", PublicName: "runSpeedSupported", Description: "是否支持运行速度", ValueType: "int", Aliases: []string{"是否支持运行速度"}},
	{ID: "sens_shield", PublicName: "sensShield", Description: "识别范围", ValueType: "int64", Aliases: []string{"识别范围"}},
	{ID: "support_fbnum", PublicName: "supportResetLockNum", Description: "支持重置锁定的数量", ValueType: "int", Aliases: []string{"support reset lock num", "支持重置锁定的数量"}},
	{ID: "srb", PublicName: "switchRebound", Description: "开关自回弹", ValueType: "int", Aliases: []string{"Switch rebound", "开关自回弹"}},
	{ID: "curp", PublicName: "currentPower", Description: "当前功率", ValueType: "int", Aliases: []string{"Current power", "当前功率"}},
	{ID: "iec", PublicName: "intervalElectricityConsumption", Description: "阶段电量，默认5分钟", ValueType: "int64", Aliases: []string{"Interval electricity consumption", "阶段电量，默认5分钟"}},
}
