package main

var moduleCommands = map[string]map[string]moduleCommandSpec{
	"account": {
		"info": {Intent: "account.info", Utterance: "查看账号信息"},
	},
	"ai-voice": {
		"list":     {Intent: "ai_voice.list", Utterance: "查看 AI 语音账号能力"},
		"products": {Intent: "ai_voice.product.list", Utterance: "查看 AI 语音支持产品"},
	},
	"area": {
		"batch-delete": {Intent: "area.batch_delete", Utterance: "批量删除区域", EntityType: "area", TargetIDKeys: []string{"area-ids", "ids"}, TargetName: true},
		"create":       {Intent: "area.create", Utterance: "创建区域"},
		"delete":       {Intent: "area.delete", Utterance: "删除区域", EntityType: "area", TargetIDKeys: []string{"area-id", "areaId", "id"}, TargetName: true},
		"detail":       {Intent: "area.detail.get", Utterance: "查看区域详情", EntityType: "area", TargetIDKeys: []string{"area-id", "areaId", "id"}, TargetName: true},
		"list":         {Intent: "geo_area.children.list", Utterance: "列出地理区域"},
		"search":       {Intent: "geo_area.search", Utterance: "搜索地理区域"},
		"update":       {Intent: "area.update", Utterance: "更新区域", EntityType: "area", TargetIDKeys: []string{"area-id", "areaId", "id"}, TargetName: true},
	},
	"automation": {
		"batch-delete": {Intent: "automation.batch_delete", Utterance: "批量删除自动化", EntityType: "automation", TargetIDKeys: []string{"automation-ids", "ids"}, TargetName: true},
		"capabilities": {Intent: "automation.capabilities", Utterance: "查看自动化能力"},
		"create":       {Intent: "automation.create", Utterance: "创建自动化"},
		"delete":       {Intent: "automation.delete", Utterance: "删除自动化", EntityType: "automation", TargetIDKeys: []string{"automation-id", "automationId", "id"}, TargetName: true},
		"detail":       {Intent: "automation.detail.get", Utterance: "查看自动化详情", EntityType: "automation", TargetIDKeys: []string{"automation-id", "automationId", "id"}, TargetName: true},
		"diagnose":     {Intent: "diagnose.automation", Utterance: "诊断自动化", EntityType: "automation", TargetIDKeys: []string{"automation-id", "automationId", "id"}, TargetName: true},
		"disable":      {Intent: "automation.disable", Utterance: "停用自动化", EntityType: "automation", TargetIDKeys: []string{"automation-id", "automationId", "id"}, TargetName: true},
		"enable":       {Intent: "automation.enable", Utterance: "启用自动化", EntityType: "automation", TargetIDKeys: []string{"automation-id", "automationId", "id"}, TargetName: true},
		"explain":      {Intent: "automation.explain", Utterance: "解释自动化", EntityType: "automation", TargetIDKeys: []string{"automation-id", "automationId", "id"}, TargetName: true},
		"list":         {Intent: "automation.list", Utterance: "列出自动化"},
		"page":         {Intent: "automation.list.page", Utterance: "分页列出自动化"},
		"rules":        {Intent: "automation.rule.list", Utterance: "列出自动化规则"},
		"supported":    {Intent: "automation.supported.list", Utterance: "查看支持的自动化能力"},
		"supported-v2": {Intent: "automation.supported.v2.list", Utterance: "查看 v2 自动化支持能力"},
		"update":       {Intent: "automation.update", Utterance: "更新自动化", EntityType: "automation", TargetIDKeys: []string{"automation-id", "automationId", "id"}, TargetName: true},
	},
	"behavior": {
		"execute": {Intent: "behavior.execute", Utterance: "执行设备行为", EntityType: "device", TargetIDKeys: []string{"device-id", "deviceId", "id"}, TargetName: true},
	},
	"device": {
		"attrs":           {Intent: "device.attr.list", Utterance: "列出设备属性", EntityType: "device", TargetIDKeys: []string{"device-id", "deviceId", "id"}, TargetName: true},
		"capabilities":    {Intent: "entity.capabilities", Utterance: "查看设备能力", EntityType: "device", TargetIDKeys: []string{"device-id", "deviceId", "id"}, TargetName: true},
		"detail":          {Intent: "device.detail.get", Utterance: "查看设备详情", EntityType: "device", TargetIDKeys: []string{"device-id", "deviceId", "id"}, TargetName: true},
		"diagnose":        {Intent: "diagnose.device", Utterance: "诊断设备", EntityType: "device", TargetIDKeys: []string{"device-id", "deviceId", "id"}, TargetName: true},
		"energy":          {Intent: "device.energy.summary", Utterance: "查看设备能耗摘要", EntityType: "device", TargetIDKeys: []string{"device-id", "deviceId", "id"}, TargetName: true},
		"list":            {Intent: "device.list", Utterance: "列出设备"},
		"move":            {Intent: "device.move", Utterance: "移动设备", EntityType: "device", TargetIDKeys: []string{"device-id", "deviceId", "id"}, TargetName: true},
		"move-room-batch": {Intent: "device.move_room.batch", Utterance: "批量移动设备到房间"},
		"remove":          {Intent: "device.remove", Utterance: "移除设备", EntityType: "device", TargetIDKeys: []string{"device-id", "deviceId", "id"}, TargetName: true},
		"rename":          {Intent: "device.rename", Utterance: "重命名设备", EntityType: "device", TargetIDKeys: []string{"device-id", "deviceId", "id"}, TargetName: true},
		"slot-create":     {Intent: "device.slot.create", Utterance: "创建设备预留槽位"},
		"state":           {Intent: "state.query", Utterance: "查询设备状态", EntityType: "device", TargetIDKeys: []string{"device-id", "deviceId", "id"}, TargetName: true},
		"storage":         {Intent: "device.storage.get", Utterance: "查看设备素材存储", EntityType: "device", TargetIDKeys: []string{"device-id", "deviceId", "id"}, TargetName: true},
		"unbind":          {Intent: "device.unbind", Utterance: "解绑设备", EntityType: "device", TargetIDKeys: []string{"device-id", "deviceId", "id"}, TargetName: true},
		"virtual-count":   {Intent: "device.virtual_count.get", Utterance: "查看虚拟设备数量"},
		"weather":         {Intent: "device.weather.get", Utterance: "查看设备天气信息", EntityType: "device", TargetIDKeys: []string{"device-id", "deviceId", "id"}, TargetName: true},
	},
	"entity": {
		"capabilities": {Intent: "entity.capabilities", Utterance: "查看实体能力", TargetIDKeys: []string{"entity-id", "entityId", "id"}, TargetName: true},
		"get":          {Intent: "entity.get", Utterance: "查看实体详情", TargetIDKeys: []string{"entity-id", "entityId", "id"}, TargetName: true},
		"list":         {Intent: "entity.list", Utterance: "列出家庭实体"},
		"rename-batch": {Intent: "entity.rename.batch", Utterance: "批量重命名实体"},
	},
	"execution": {
		"undo": {Intent: "execution.undo", Utterance: "撤销执行", TargetIDKeys: []string{"execution-id", "executionId", "id"}},
	},
	"favorite": {
		"add":          {Intent: "favorite.add", Utterance: "新增收藏"},
		"batch-add":    {Intent: "favorite.batch_add", Utterance: "批量新增收藏"},
		"batch-delete": {Intent: "favorite.batch_delete", Utterance: "批量删除收藏", TargetIDKeys: []string{"favorite-ids", "ids"}},
		"batch-update": {Intent: "favorite.batch_update", Utterance: "批量更新收藏"},
		"delete":       {Intent: "favorite.delete", Utterance: "删除收藏", TargetIDKeys: []string{"favorite-id", "favoriteId", "id"}},
		"list":         {Intent: "favorite.list", Utterance: "列出收藏"},
		"plan":         {Intent: "favorite.plan", Utterance: "规划收藏"},
		"update":       {Intent: "favorite.update", Utterance: "更新收藏", TargetIDKeys: []string{"favorite-id", "favoriteId", "id"}},
	},
	"gateway": {
		"configure":       {Intent: "gateway.configure", Utterance: "配置网关", EntityType: "device", TargetIDKeys: []string{"gateway-id", "gatewayId", "device-id", "deviceId", "id"}, TargetName: true},
		"delete":          {Intent: "gateway.delete", Utterance: "删除网关", EntityType: "device", TargetIDKeys: []string{"gateway-id", "gatewayId", "device-id", "deviceId", "id"}, TargetName: true},
		"detail":          {Intent: "gateway.detail.get", Utterance: "查看网关详情", EntityType: "device", TargetIDKeys: []string{"gateway-id", "gatewayId", "device-id", "deviceId", "id"}, TargetName: true},
		"diagnose":        {Intent: "diagnose.gateway", Utterance: "诊断网关", EntityType: "device", TargetIDKeys: []string{"gateway-id", "gatewayId", "device-id", "deviceId", "id"}, TargetName: true},
		"list":            {Intent: "gateway.list", Utterance: "列出网关"},
		"scene-relations": {Intent: "gateway.scene_relation.list", Utterance: "查看网关情景关联"},
		"stats":           {Intent: "gateway.stats.list", Utterance: "查看网关统计"},
		"thread":          {Intent: "gateway.thread.get", Utterance: "查看网关 Thread 信息", EntityType: "device", TargetIDKeys: []string{"gateway-id", "gatewayId", "device-id", "deviceId", "id"}, TargetName: true},
	},
	"group": {
		"batch-delete": {Intent: "group.batch_delete", Utterance: "批量删除设备组", EntityType: "group", TargetIDKeys: []string{"group-ids", "ids"}, TargetName: true},
		"create":       {Intent: "group.create", Utterance: "创建设备组"},
		"delete":       {Intent: "group.delete", Utterance: "删除设备组", EntityType: "group", TargetIDKeys: []string{"group-id", "groupId", "id"}, TargetName: true},
		"detail":       {Intent: "group.detail.get", Utterance: "查看设备组详情", EntityType: "group", TargetIDKeys: []string{"group-id", "groupId", "id"}, TargetName: true},
		"list":         {Intent: "group.list", Utterance: "列出设备组"},
		"search":       {Intent: "group.search", Utterance: "搜索设备组"},
		"structure":    {Intent: "group.structure.list", Utterance: "查看设备组结构"},
		"update":       {Intent: "group.update", Utterance: "更新设备组", EntityType: "group", TargetIDKeys: []string{"group-id", "groupId", "id"}, TargetName: true},
	},
	"home": {
		"accept-share":     {Intent: "home.member.accept_share", Utterance: "接受家庭分享", TargetIDKeys: []string{"share-id", "shareId", "id"}},
		"create":           {Intent: "home.create", Utterance: "新增家庭"},
		"current-member":   {Intent: "home.member.current.get", Utterance: "查看当前家庭成员信息"},
		"delete":           {Intent: "home.delete", Utterance: "删除家庭", TargetIDKeys: []string{"house-id", "houseId", "id"}},
		"detail":           {Intent: "home.detail.get", Utterance: "查看家庭详情"},
		"invite":           {Intent: "home.member.invite", Utterance: "生成或发送家庭邀请"},
		"list":             {Intent: "home.list", Utterance: "列出家庭"},
		"lock-all":         {Intent: "home.lock_all", Utterance: "家庭全关或锁定"},
		"member-configure": {Intent: "home.member.configure", Utterance: "更新家庭成员角色", TargetIDKeys: []string{"member-id", "memberId", "id"}},
		"member-remove":    {Intent: "home.member.remove", Utterance: "移除家庭成员", TargetIDKeys: []string{"member-id", "memberId", "id"}},
		"member-transfer":  {Intent: "home.member.transfer", Utterance: "转移家庭管理员权限", TargetIDKeys: []string{"member-id", "memberId", "id"}},
		"members":          {Intent: "home.member.list", Utterance: "列出家庭成员"},
		"quit":             {Intent: "home.member.quit", Utterance: "退出分享家庭"},
		"search":           {Intent: "home.search", Utterance: "搜索家庭"},
		"sort":             {Intent: "home.sort.list", Utterance: "查看首页排序"},
		"sort-configure":   {Intent: "home.sort.configure", Utterance: "配置首页排序"},
		"stat":             {Intent: "home.stat.get", Utterance: "查看家庭统计"},
		"summary":          {Intent: "home.summary", Utterance: "查看家庭概况"},
		"unlock-all":       {Intent: "home.unlock_all", Utterance: "家庭全开或解锁"},
		"update":           {Intent: "home.update", Utterance: "更新家庭"},
	},
	"light": {
		"brightness":        {Intent: "light.brightness.set", Utterance: "设置灯光亮度", EntityType: "device", TargetIDKeys: []string{"device-id", "deviceId", "id"}, TargetName: true},
		"brightness-adjust": {Intent: "light.brightness.adjust", Utterance: "调节灯光亮度", EntityType: "device", TargetIDKeys: []string{"device-id", "deviceId", "id"}, TargetName: true},
		"color":             {Intent: "light.color.set", Utterance: "设置灯光颜色", EntityType: "device", TargetIDKeys: []string{"device-id", "deviceId", "id"}, TargetName: true},
		"ct":                {Intent: "light.color_temperature.set", Utterance: "设置灯光色温", EntityType: "device", TargetIDKeys: []string{"device-id", "deviceId", "id"}, TargetName: true},
		"ct-adjust":         {Intent: "light.color_temperature.adjust", Utterance: "调节灯光色温", EntityType: "device", TargetIDKeys: []string{"device-id", "deviceId", "id"}, TargetName: true},
		"experience":        {Intent: "lighting.experience.apply", Utterance: "应用灯光体验", EntityType: "device", TargetIDKeys: []string{"device-id", "deviceId", "id"}, TargetName: true},
		"off":               {Intent: "light.power.set", Utterance: "关闭灯光", EntityType: "device", TargetIDKeys: []string{"device-id", "deviceId", "id"}, TargetName: true},
		"on":                {Intent: "light.power.set", Utterance: "打开灯光", EntityType: "device", TargetIDKeys: []string{"device-id", "deviceId", "id"}, TargetName: true},
	},
	"lighting": {
		"apply":      {Intent: "lighting.design.apply", Utterance: "应用灯光设计方案", TargetIDKeys: []string{"plan-id", "planId", "id"}},
		"experience": {Intent: "lighting.experience.apply", Utterance: "应用灯光体验", EntityType: "device", TargetIDKeys: []string{"device-id", "deviceId", "id"}, TargetName: true},
		"import":     {Intent: "lighting.design.import", Utterance: "导入照明设计并预建设备槽位"},
		"plan":       {Intent: "lighting.design.plan", Utterance: "规划灯光设计"},
	},
	"memory": {
		"forget":   {Intent: "memory.forget", Utterance: "删除本地记忆"},
		"list":     {Intent: "memory.list", Utterance: "列出本地记忆"},
		"pause":    {Intent: "memory.pause", Utterance: "暂停本地学习"},
		"remember": {Intent: "memory.remember", Utterance: "保存本地记忆"},
		"resume":   {Intent: "memory.resume", Utterance: "恢复本地学习"},
	},
	"meshgroup": {
		"detail": {Intent: "meshgroup.detail.get", Utterance: "查看 Mesh 组详情", TargetIDKeys: []string{"meshgroup-id", "meshgroupId", "group-id", "groupId", "id"}},
	},
	"message": {
		"list": {Intent: "message.list", Utterance: "列出消息"},
	},
	"node": {
		"property-config": {Intent: "node.property_config.get", Utterance: "查看节点属性配置", TargetIDKeys: []string{"node-id", "nodeId", "id"}},
		"sorted-devices":  {Intent: "node.sorted_device.list", Utterance: "查看节点排序设备"},
	},
	"operation": {
		"batch-configure": {Intent: "operation.batch.configure", Utterance: "批量配置添加或修改操作"},
	},
	"knob": {
		"configure": {Intent: "knob.configure", Utterance: "配置旋钮", EntityType: "device", TargetIDKeys: []string{"knob-id", "knobId", "device-id", "deviceId", "id"}, TargetName: true},
		"detail":    {Intent: "knob.get", Utterance: "查看旋钮详情", EntityType: "device", TargetIDKeys: []string{"knob-id", "knobId", "device-id", "deviceId", "id"}, TargetName: true},
		"reset":     {Intent: "knob.reset", Utterance: "重置旋钮", EntityType: "device", TargetIDKeys: []string{"knob-id", "knobId", "device-id", "deviceId", "id"}, TargetName: true},
	},
	"panel": {
		"button-configure":     {Intent: "panel.button.configure", Utterance: "配置面板按键", EntityType: "device", TargetIDKeys: []string{"panel-id", "panelId", "device-id", "deviceId", "id"}, TargetName: true},
		"button-event-reset":   {Intent: "panel.button_event.reset", Utterance: "重置面板按键事件", EntityType: "device", TargetIDKeys: []string{"button-event-id", "buttonEventId", "id"}, TargetName: true},
		"button-event-update":  {Intent: "panel.button_event.update", Utterance: "更新面板按键事件", EntityType: "device", TargetIDKeys: []string{"button-event-id", "buttonEventId", "id"}, TargetName: true},
		"button-events-update": {Intent: "panel.button_event.batch_update", Utterance: "批量更新面板按键事件", EntityType: "device", TargetIDKeys: []string{"panel-id", "panelId", "device-id", "deviceId", "id"}, TargetName: true},
		"buttons":              {Intent: "panel.button.type.get", Utterance: "查看面板按键类型", EntityType: "device", TargetIDKeys: []string{"device-id", "deviceId", "id"}, TargetName: true},
		"detail":               {Intent: "panel.get", Utterance: "查看面板详情", EntityType: "device", TargetIDKeys: []string{"device-id", "deviceId", "id"}, TargetName: true},
		"list":                 {Intent: "panel.list", Utterance: "列出面板"},
		"screen-controls":      {Intent: "screen.control.list", Utterance: "查看屏幕控制列表", EntityType: "device", TargetIDKeys: []string{"device-id", "deviceId", "id"}, TargetName: true},
	},
	"plan": {
		"cancel": {Intent: "plan.cancel", Utterance: "取消待确认计划", TargetIDKeys: []string{"plan-id", "planId", "id"}},
		"commit": {Intent: "plan.commit", Utterance: "提交待确认计划", TargetIDKeys: []string{"plan-id", "planId", "id"}},
	},
	"product": {
		"pedia":  {Intent: "product.pedia.search", Utterance: "搜索产品百科资料"},
		"search": {Intent: "product.pedia.search", Utterance: "搜索产品百科资料"},
	},
	"progress": {
		"get": {Intent: "progress.get", Utterance: "查看进度", TargetIDKeys: []string{"progress-id", "progressId", "id"}},
	},
	"recommendation": {
		"feedback": {Intent: "recommendation.feedback", Utterance: "反馈推荐"},
		"list":     {Intent: "recommendation.list", Utterance: "列出推荐"},
	},
	"room": {
		"area-configure": {Intent: "room.area.configure", Utterance: "调整房间区域", EntityType: "room", TargetIDKeys: []string{"room-id", "roomId", "id"}, TargetName: true},
		"batch-create":   {Intent: "room.batch_create", Utterance: "批量创建房间"},
		"batch-delete":   {Intent: "room.batch_delete", Utterance: "批量删除房间", EntityType: "room", TargetIDKeys: []string{"room-ids", "ids"}, TargetName: true},
		"batch-update":   {Intent: "room.batch_update", Utterance: "批量更新房间"},
		"create":         {Intent: "room.create", Utterance: "创建房间"},
		"delete":         {Intent: "room.delete", Utterance: "删除房间", EntityType: "room", TargetIDKeys: []string{"room-id", "roomId", "id"}, TargetName: true},
		"detail":         {Intent: "room.detail.get", Utterance: "查看房间详情", EntityType: "room", TargetIDKeys: []string{"room-id", "roomId", "id"}, TargetName: true},
		"list":           {Intent: "room.list", Utterance: "列出房间"},
		"rename":         {Intent: "room.rename", Utterance: "重命名房间", EntityType: "room", TargetIDKeys: []string{"room-id", "roomId", "id"}, TargetName: true},
		"search":         {Intent: "room.search", Utterance: "搜索房间"},
		"update":         {Intent: "room.update", Utterance: "更新房间", EntityType: "room", TargetIDKeys: []string{"room-id", "roomId", "id"}, TargetName: true},
	},
	"schedule": {
		"jobs": {Intent: "schedule_job.list", Utterance: "列出定时任务"},
	},
	"scene": {
		"batch-delete": {Intent: "scene.batch_delete", Utterance: "批量删除情景", EntityType: "scene", TargetIDKeys: []string{"scene-ids", "ids"}, TargetName: true},
		"create":       {Intent: "scene.create", Utterance: "创建情景"},
		"delete":       {Intent: "scene.delete", Utterance: "删除情景", EntityType: "scene", TargetIDKeys: []string{"scene-id", "sceneId", "id"}, TargetName: true},
		"detail":       {Intent: "scene.detail.get", Utterance: "查看情景详情", EntityType: "scene", TargetIDKeys: []string{"scene-id", "sceneId", "id"}, TargetName: true},
		"diagnose":     {Intent: "diagnose.scene", Utterance: "诊断情景", EntityType: "scene", TargetIDKeys: []string{"scene-id", "sceneId", "id"}, TargetName: true},
		"execute":      {Intent: "scene.execute", Utterance: "执行情景", EntityType: "scene", TargetIDKeys: []string{"scene-id", "sceneId", "id"}, TargetName: true},
		"list":         {Intent: "scene.list", Utterance: "列出情景"},
		"scoped-list":  {Intent: "scene.scoped.list", Utterance: "列出范围内情景"},
		"search":       {Intent: "scene.search", Utterance: "搜索情景"},
		"test":         {Intent: "scene.test", Utterance: "测试情景", EntityType: "scene", TargetIDKeys: []string{"scene-id", "sceneId", "id"}, TargetName: true},
		"update":       {Intent: "scene.update", Utterance: "更新情景", EntityType: "scene", TargetIDKeys: []string{"scene-id", "sceneId", "id"}, TargetName: true},
	},
	"screen": {
		"controls": {Intent: "screen.control.list", Utterance: "查看屏幕控制列表", EntityType: "device", TargetIDKeys: []string{"device-id", "deviceId", "id"}, TargetName: true},
	},
	"sensor": {
		"events": {Intent: "sensor.event.list", Utterance: "列出传感器事件", EntityType: "device", TargetIDKeys: []string{"sensor-id", "sensorId", "device-id", "deviceId", "id"}, TargetName: true},
		"list":   {Intent: "sensor.list", Utterance: "列出传感器"},
	},
	"thing": {
		"category":         {Intent: "thing.category.list", Utterance: "列出物模型品类"},
		"categories":       {Intent: "thing.category.list", Utterance: "列出物模型品类"},
		"component":        {Intent: "thing.component.get", Utterance: "查看物模型组件", TargetIDKeys: []string{"component-id", "componentId", "id"}},
		"components":       {Intent: "thing.component.list", Utterance: "列出物模型组件"},
		"domains":          {Intent: "thing.product_domain.list", Utterance: "列出产品域"},
		"product-domain":   {Intent: "thing.product_domain.list", Utterance: "列出产品域"},
		"product-domains":  {Intent: "thing.product_domain.list", Utterance: "列出产品域"},
		"faq-detail":       {Intent: "thing.product_faq.detail.get", Utterance: "查看产品 FAQ 详情", TargetIDKeys: []string{"faq-id", "faqId", "id"}},
		"faq-item-types":   {Intent: "thing.product_faq.item_type.list", Utterance: "列出产品 FAQ 条目类型"},
		"faq-locales":      {Intent: "thing.product_faq.locale.list", Utterance: "列出产品 FAQ 语言"},
		"faq-page-details": {Intent: "thing.product_faq.page_detail.list", Utterance: "列出产品 FAQ 页面详情"},
		"faq-pages":        {Intent: "thing.product_faq.page.list", Utterance: "列出产品 FAQ 页面"},
		"faq-types":        {Intent: "thing.product_faq.type.list", Utterance: "列出产品 FAQ 类型"},
		"faqs":             {Intent: "thing.product_faq.list", Utterance: "列出产品 FAQ"},
		"product-info":     {Intent: "thing.product.info.batch_get", Utterance: "批量查看产品信息"},
		"product-info-v3":  {Intent: "thing.product.info.v3.batch_get", Utterance: "批量查看 v3 产品信息"},
		"products":         {Intent: "thing.product.list.v3", Utterance: "列出产品定义"},
		"properties":       {Intent: "thing.property.list", Utterance: "列出物模型属性"},
		"schema":           {Intent: "thing.schema.list", Utterance: "列出物模型 schema"},
		"schema-detail":    {Intent: "thing.schema.detail.list", Utterance: "列出物模型 schema 详情"},
		"schema-events":    {Intent: "thing.schema.event.list", Utterance: "列出物模型事件"},
		"schema-get":       {Intent: "thing.schema.get", Utterance: "查看物模型 schema", TargetIDKeys: []string{"schema-id", "schemaId", "id"}},
	},
	"upgrade": {
		"app-latest":  {Intent: "app_upgrade.latest.get", Utterance: "查看 App 升级最新版本"},
		"batch-files": {Intent: "upgrade.file.batch_list", Utterance: "批量查看升级文件"},
		"files":       {Intent: "upgrade.file.list", Utterance: "列出升级文件"},
		"ota-files":   {Intent: "ota.version_file.batch_list", Utterance: "批量查看 OTA 版本文件"},
		"progress":    {Intent: "upgrade.progress.get", Utterance: "查看升级进度"},
	},
}
